### ISSUE TITLE
auth 상태 관리 개선

### ISSUE THREAD

**Issue by xxziiko** [xxziiko/grape#2]
### Issue
- jotai 도입하여 인증관리 프로세스 개선

### Task
- [x] context api 제거
- [x] jotai로 인증 상태관리
- [x] 변경 사항에 대한 테스트
